language: node_js
sudo: false
node_js:
- '5.0.0'

cache:
  directories:
    - node_modules

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/51f75e331838d36801f2
    on_success: change
    on_failure: always
    on_start: never

addons:
  firefox: '38.0'
  
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
- node_modules/.bin/gulp build
- node_modules/.bin/gulp test